
vesper-center:
  system:
    version-name: 0.0.1-dev
    version-code: 1
    build-time: 2024-04-12T17:00+08:00
  session:
    token-expire-milliseconds: 3600000  # 60分钟
    ticket-locker-file:
      # vesper center 停止时，缓存 ticket locker 的位置。
      # 设为 'none' 以禁用缓存。
      dump-path: '/home/flowerblack/Desktop/vesper-center-session.txt'
      dump-key: '0123456789abcdef'

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/vesper-center
    username: flowerblack
    password: 123456

  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 32MB

  output:
    ansi:
      enabled: ALWAYS

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

server:
  # vesper center 运行的端口
  port: 9000
  error:
    whitelabel:
      enable: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
