
vesper-center:
  system:
    version-name: 1.6.0
    version-code: 16
    build-time: 2024-09-09T17:33+08:00
  data-dir: ${VESPER_CENTER_DATA_DIR}
  session:
    token-expire-milliseconds: 3600000  # 60分钟
    ticket-locker-file:
      # vesper center 停止时，缓存 ticket locker 的位置。
      # 设为 'none' 以禁用缓存。
      enable-dump: ${VESPER_CENTER_TICKET_LOCKER_ENABLE_DUMP:false}
      dump-key: '0123456789abcdef'
  cors:
    # example: https:/xxx.com,http://xxx.cn,http://...  which is comma splitted.
    allowed-origins: ${VESPER_CENTER_CORS_ALLOWED_ORIGINS}

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/vesper-center
    username: ${VESPER_CENTER_DB_USERNAME}
    password: ${VESPER_CENTER_DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 32MB

  output:
    ansi:
      enabled: ALWAYS

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

server:
  # vesper center 运行的端口
  port: ${VESPER_CENTER_WEB_SERVER_PORT:9000}
  ssl:
    key-store: ${VESPER_CENTER_SSL_KEY_STORE}
    key-store-password: ${VESPER_CENTER_SSL_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
  error:
    whitelabel:
      enable: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  global-config:
    db-config:
      # IGNORED or NOT_NULL or NOT_EMPTY
      update-strategy: IGNORED
